name: Close stale PRs

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-close: 1
          days-before-stale: 1
          exempt-pr-labels: 'RFC,Waiting on Review'
          only-issue-labels: 'inexistent-label'
          stale-pr-message: >
            This PR is automatically being closed because there hasn't been any recent activity.
            Feel free to reopen it when development continues.
